import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

export const metadata = {
  title: "Terms of Service — OptimumAI",
  description: "The terms governing your use of OptimumAI's platform, programs, and services.",
}

export default function TermsPage() {
  return (
    <>
      <Header />
      <main className="optimum-main">
        <div className="grain-overlay" aria-hidden="true" />
        <div className="opt-page">

          <p className="opt-kicker">Legal</p>
          <h1 className="opt-headline" style={{ fontSize: "clamp(36px, 5vw, 64px)" }}>
            Terms of<br /><em>Service</em>
          </h1>
          <p className="opt-sub">Effective: March 15, 2026 &nbsp;·&nbsp; OptimumAI, Inc.</p>

          <div className="opt-legal-body">

            <p>
              Welcome to OptimumAI. These Terms of Service ("Terms") govern your access to and use of
              OptimumAI's website, research platform, bootcamps, internship marketplace, community tools, and
              all related services (collectively, "Services"), provided by OptimumAI, Inc. ("OptimumAI", "we",
              "our", or "us"). By creating an account or using our Services you agree to these Terms. If you do
              not agree, do not use our Services.
            </p>

            {/* ── 1 ── */}
            <div className="opt-rule"><span className="opt-rule-text">1. Eligibility & Registration</span></div>

            <p>
              <strong>Minimum age.</strong> You must be at least 13 years old to use our Services, and at least 18
              (or the age of majority in your jurisdiction) to independently enter into these Terms. Users aged
              13–17 must have parental or guardian consent.
            </p>
            <p>
              <strong>Account accuracy.</strong> You agree to provide accurate, current, and complete information
              when registering. You are responsible for maintaining the confidentiality of your credentials and
              for all activity under your account. Notify us immediately at <strong>support@optimumai.in</strong> if
              you suspect unauthorised access.
            </p>
            <p>
              <strong>One account per person.</strong> You may not create multiple accounts or share account
              access. Accounts are non-transferable.
            </p>

            {/* ── 2 ── */}
            <div className="opt-rule"><span className="opt-rule-text">2. Acceptable Use</span></div>

            <h3 className="opt-legal-h3">You may</h3>
            <ul className="opt-legal-list">
              <li>Access and use our research tools, bootcamp content, and community features for lawful educational and research purposes.</li>
              <li>Publish research outputs created with our platform, subject to attribution requirements.</li>
              <li>Collaborate with other members in good faith and in accordance with our Community Guidelines.</li>
            </ul>

            <h3 className="opt-legal-h3">You may not</h3>
            <ul className="opt-legal-list">
              <li>Use the Services to infringe intellectual property rights, distribute malware, or engage in any unlawful activity.</li>
              <li>Attempt to reverse-engineer, decompile, or extract source code from our AI models, algorithms, or systems.</li>
              <li>Scrape, crawl, or programmatically extract data from our platform without prior written permission.</li>
              <li>Represent AI-generated outputs as human-authored research without disclosure.</li>
              <li>Circumvent rate limits, access controls, or safety measures built into our Services.</li>
              <li>Use our Services to develop competing AI research tools or platforms.</li>
              <li>Harass, threaten, or harm other community members.</li>
              <li>Upload content that is defamatory, obscene, or violates the rights of any third party.</li>
            </ul>

            {/* ── 3 ── */}
            <div className="opt-rule"><span className="opt-rule-text">3. Content & Intellectual Property</span></div>

            <h3 className="opt-legal-h3">Your content</h3>
            <p>
              You retain ownership of research papers, submissions, and other original content you upload
              ("Your Content"). By uploading content, you grant OptimumAI a worldwide, non-exclusive,
              royalty-free licence to host, display, and distribute Your Content solely to operate and improve
              the Services. You represent that you have all necessary rights to grant this licence.
            </p>

            <h3 className="opt-legal-h3">AI-generated outputs</h3>
            <p>
              To the extent permitted by applicable law, outputs generated by OptimumAI's tools based on your
              inputs ("Outputs") are assigned to you. Because AI outputs are probabilistic, they may not be
              unique; the same assignment does not extend to identical outputs generated for other users.
              You are responsible for evaluating Outputs for accuracy before relying on them.
            </p>

            <h3 className="opt-legal-h3">OptimumAI's intellectual property</h3>
            <p>
              All rights, title, and interest in our platform, models, interfaces, brand, and original content
              belong to OptimumAI. Nothing in these Terms grants you rights to our intellectual property except
              the limited licence to use the Services.
            </p>

            <h3 className="opt-legal-h3">Feedback</h3>
            <p>
              Any feedback, suggestions, or ideas you provide about the Services may be used by OptimumAI
              without restriction or compensation to you.
            </p>

            {/* ── 4 ── */}
            <div className="opt-rule"><span className="opt-rule-text">4. Programs, Payments & Cancellations</span></div>

            <h3 className="opt-legal-h3">Paid programs</h3>
            <p>
              Certain bootcamps, certifications, and internship-placement services require payment. By enrolling
              you authorise us to charge your payment method for the stated fee. All prices are listed in USD
              and are inclusive of any advertised discounts. We will give at least 30 days' notice of price
              changes to existing subscribers.
            </p>

            <h3 className="opt-legal-h3">Refunds</h3>
            <p>
              You may request a full refund within 7 days of purchase, provided you have not completed more than
              20% of a bootcamp's content. After this window, refunds are at OptimumAI's discretion except where
              required by applicable consumer protection law.
            </p>

            <h3 className="opt-legal-h3">Cancellation</h3>
            <p>
              You may cancel a subscription at any time from your account settings. Cancellation takes effect at
              the end of the current billing period. No partial-period refunds are issued except where required
              by law.
            </p>

            {/* ── 5 ── */}
            <div className="opt-rule"><span className="opt-rule-text">5. AI Research Tools — Important Notices</span></div>

            <p>
              OptimumAI's research assistance tools use machine learning models. When using these tools you
              acknowledge:
            </p>
            <ul className="opt-legal-list">
              <li>Outputs may be incomplete, inaccurate, or reflect biases present in training data.</li>
              <li>You must not rely on Outputs as a sole source of truth or as a substitute for expert review.</li>
              <li>You must not use Outputs to make decisions with material legal, financial, medical, or safety consequences for others without appropriate human review.</li>
              <li>OptimumAI does not warrant that AI-generated literature recommendations are exhaustive or free of error.</li>
            </ul>

            {/* ── 6 ── */}
            <div className="opt-rule"><span className="opt-rule-text">6. Termination & Suspension</span></div>

            <p>
              You may close your account at any time via account settings. We may suspend or terminate your
              access if we determine that you have breached these Terms, violated our Acceptable Use Policy, or
              if continued access poses risk to OptimumAI, other users, or third parties. Where feasible, we
              will give you prior notice and the opportunity to appeal to <strong>appeals@optimumai.org</strong>.
            </p>
            <p>
              Accounts that are inactive for more than 24 months with no paid subscription may be closed after
              30 days' notice to the email address on file.
            </p>

            {/* ── 7 ── */}
            <div className="opt-rule"><span className="opt-rule-text">7. Disclaimer of Warranties</span></div>

            <p>
              THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM
              EXTENT PERMITTED BY LAW, OPTIMUMAI DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
              WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY
              OF INFORMATIONAL CONTENT. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE,
              OR FREE OF HARMFUL COMPONENTS.
            </p>

            {/* ── 8 ── */}
            <div className="opt-rule"><span className="opt-rule-text">8. Limitation of Liability</span></div>

            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, OPTIMUMAI AND ITS AFFILIATES, OFFICERS,
              EMPLOYEES, AND LICENSORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
              OR PUNITIVE DAMAGES, OR LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF OR INABILITY
              TO USE THE SERVICES. OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIM ARISING FROM THESE TERMS OR THE
              SERVICES WILL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE
              CLAIM OR USD $100.
            </p>
            <p>
              Some jurisdictions do not permit exclusion of certain warranties or limitation of certain damages.
              Where this is the case, these limitations apply only to the extent permitted by local law.
            </p>

            {/* ── 9 ── */}
            <div className="opt-rule"><span className="opt-rule-text">9. Indemnification</span></div>

            <p>
              If you use our Services on behalf of an organisation, you agree to indemnify, defend, and hold
              harmless OptimumAI and its personnel from and against any claims, liabilities, damages, and
              expenses (including reasonable legal fees) arising from your or your organisation's use of the
              Services or violation of these Terms.
            </p>

            {/* ── 10 ── */}
            <div className="opt-rule"><span className="opt-rule-text">10. Governing Law & Disputes</span></div>

            <p>
              These Terms are governed by the laws of the State of Delaware, USA, without regard to conflict-of-law
              principles. Before initiating formal proceedings, both parties agree to make a good-faith effort to
              resolve disputes informally by contacting <strong>legal@optimumai.org</strong>. If the dispute is not
              resolved within 60 days, either party may pursue available legal remedies.
            </p>
            <p>
              For users in the European Economic Area or United Kingdom, mandatory local consumer protection laws
              apply and are not affected by these Terms.
            </p>

            {/* ── 11 ── */}
            <div className="opt-rule"><span className="opt-rule-text">11. Changes to These Terms</span></div>

            <p>
              We may update these Terms from time to time. Material changes will be notified by email or
              in-product notice at least 30 days before they take effect. Continued use after the effective
              date constitutes acceptance. If you do not agree, please stop using the Services and close your
              account.
            </p>

            {/* ── 12 ── */}
            <div className="opt-rule"><span className="opt-rule-text">12. General Provisions</span></div>

            <ul className="opt-legal-list">
              <li><strong>Entire agreement.</strong> These Terms, together with our Privacy Policy and Cookie Policy, constitute the entire agreement between you and OptimumAI regarding the Services.</li>
              <li><strong>Severability.</strong> If any provision is held invalid or unenforceable, the remainder will continue in full force.</li>
              <li><strong>No waiver.</strong> Failure to enforce any provision is not a waiver of that right.</li>
              <li><strong>Assignment.</strong> You may not assign these Terms without our prior written consent. We may assign our rights to an affiliate or successor without restriction.</li>
              <li><strong>Trade controls.</strong> You must comply with all applicable export control and sanctions laws when using our Services.</li>
            </ul>

            {/* ── 13 ── */}
            <div className="opt-rule"><span className="opt-rule-text">13. Contact</span></div>

            <p>
              Questions about these Terms?<br />
              <strong>Email:</strong> legal@optimumai.org<br />
              <strong>Mail:</strong> OptimumAI, Inc. · Attn: Legal Team · [Address on file]
            </p>

          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
